<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // Promise异常穿透，当使用promise的then链式调用时，可以在最后指定失败的回调，前面任何操作出了异常，都会传到最后失败的回调中处理
    // 中断Promise链，当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数，办法：在回调函数中返回一个pending状态的promise对象
    // Promise.then返回的新Promise的结束状态由什么决定？
    // 由then指定的回调函数执行结果决定
    //  1.如果抛出异常，新Promise变为rejected，err为抛出异常
    //  2.如果返回的是非promise的任何值，新promise变为resolved，value为返回的值
    //  3.如果返回的是另一个新的promise，此promise的结果就会成为新的promise的结果

    new Promise((resolve, reject) => {
      // resolve(1)
      reject(1);
    }).then(value => {
      console.log('onResolved1', value)
      return 2;
    })
    .then(value=> {
      console.log('onResolved2', value)
      return 3;
    }).then(value=> {
      console.log('onResolved3', value);
    }).catch(err=> {
      console.log('onRejected1',err)
      // throw err
      // Promise.reject(err)
      return new Promise(() => {}); // 返回一个pending的Promisee
    }).then(value=> {
      console.log(value)
    }, err=> {
      console.log(err)
    })

  </script>
</body>
</html>